version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017

  frontend:
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
      - ./front/templates:/usr/share/nginx/html
      - ./front/static:/usr/share/nginx/static
      - ./front/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

volumes:
  mongodb_data: